version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: partner
      POSTGRES_USER: partner
      POSTGRES_PASSWORD: partner
    ports:
      - "5432:5432"

  app:
    build: .
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/partner
      SPRING_DATASOURCE_USERNAME: partner
      SPRING_DATASOURCE_PASSWORD: partner
    ports:
      - "8080:8080"